fragment BlogParts on Blog {
  __typename
  title
  pubDate
  description
  author
  image
  tags
  body
  imageGallery {
    __typename
    title
    description
    gallery {
      __typename
      mediaType
      image
      vimeoUrl
      title
      caption
    }
  }
}

fragment GalleryParts on Gallery {
  __typename
  mediaType
  image
  vimeoUrl
  pubDate
  title
  caption
}

fragment FaqsParts on Faqs {
  __typename
  question
  sortPriority
  body
}
